#!/bin/sh

#
# Xiange Initramfs init file
#
#	by Lihui Zhang <swordhuihui@gmail.com>
#	2014.05.20
#
#	$1 is squasfs image file, with xiang-root(xg64.img)
#	$2 is cow.out file, for squashfs writing.
#	$3 is final mount point. [optional]
#

NORMAL="\\033[0;39m" # Standard console grey
SUCCESS="\\033[1;32m" # Success is green
WARNING="\\033[1;33m" # Warnings are yellow
FAILURE="\\033[1;31m" # Failures are red
INFO="\\033[1;36m" # Information is light cyan
BRACKET="\\033[1;34m" # Brackets are blue

#show info in cyan color, $1 is information.
showinfo()
{
	echo -e  $INFO"$1"$NORMAL
}

#show OK message in green color, $1 is information.
showOK()
{
	echo -e $SUCCESS"$1"$NORMAL
}

#show OK message in green color, $1 is information.
showFailed()
{
	echo -e $FAILURE"$1"$NORMAL
}

#check return code. show $1 if error.
err_check()
{
	if [ $? != 0 ]; then
		showFailed "$1"
		/bin/sh
	fi
}

wait_root()
{
	rootdev=$(blkid | sed "s/\"//g" | grep $rootid | grep -o "^[^:]*")

	if [ "x$rootdev" != "x" ]; then
		return 0
	else
		return 1
	fi
}

showinfo "Preparing Xiange system ..."
mount -t sysfs -o nodev,noexec,nosuid sysfs /sys
err_check "mount sys failed."
mount -t proc -o nodev,noexec,nosuid proc /proc
err_check "mount proc failed."
mount -t devtmpfs none /dev
err_check "mount dev failed."

#check safemode
safemode=$(cat /proc/cmdline | grep "safemode")
if [ "$?" == "0" ]; then
	showinfo "running in safemode..."
	/bin/sh
fi

rootid=$(cat /proc/cmdline | grep -o "root=[^ ]*" | sed "s/root=//g")
err_check "get rootid failed."
showinfo "waiting root $rootid "

i=0
while [ "$i" != "60" ];
do
	i=$(($i+1))
	wait_root
	if [ "$?" == "0" ]; then
		break
	else
		printf "."
		sleep 1
		continue
	fi
done

if [ "x$rootdev" == "x" ]; then
	echo "!"
	echo ""
	showFailed "$rootid is not found, enter failsafe mode."
	/bin/sh
fi

xgb_arch=$(uname -m)
ddmntp=/tmp
finalmnt=/mnt
srcfile=$ddmntp/xiange/xiange-sqroot-$xgb_arch
cowfile=$ddmntp/xiange/cow-${xgb_arch}.out


showOK " OK"
showinfo "Found $rootdev, mounting $xgb_arch..."
mount $rootdev $ddmntp
if [ "$?" != "0" ]; then
	showFailed "mount $rootdev to $ddmntp failed, enter failsafe mode"
	/bin/sh
fi

#modules
modprobe squashfs
err_check "load squshfs failed."
modprobe loop
err_check "load loop failed."
modprobe dm-snapshot
err_check "load dm-snapshot failed."


#mount squshfs
mount "$srcfile" /mnt -o loop=/dev/loop7
err_check "mount $1 to /mnt failed."

losetup -o $((63*512)) /dev/loop6 /mnt/xg64.img
err_check "setup /mnt/xg64.img to /dev/loop7 failed."

mkdir -p /dev/cow 
err_check "create /dev/cow failed."
if [ -b /dev/cow/ctl ]; then
	showinfo "/dev/cow/ctl ok"
else
	mknod /dev/cow/ctl b 241 255 
	err_check "create /dev/cow/ctl failed."
fi

if [ -b /dev/cow/0 ]; then
	showinfo "/dev/cow/0 OK"
else
	mknod /dev/cow/0 b 241 0 
	err_check "create /dev/cow/0 failed."
fi

#mount cow
losetup /dev/loop5 "$cowfile"
err_check "setup cow file $cowfile to /dev/loop5 failed."

echo "0 $(blockdev --getsize /dev/loop6) snapshot /dev/loop6 /dev/loop5 p 64" | dmsetup create root_fs
err_check "create root_fs failed."

mount /dev/mapper/root_fs "$finalmnt"
err_check "mount failed."

showinfo "all done, booting..."
mount -t devtmpfs none $finalmnt/dev
exec switch_root -c /dev/console $finalmnt /sbin/init
